Vagrant.configure(2) do |config|
  config.vm.box = "tknerr/baseimage-ubuntu-18.04"
  config.vm.provision "chef_zero" do |chef|
    chef.version = "14.12.3"
    chef.installer_download_path = "/tmp/vagrant-cache/"
    chef.nodes_path = "."
    chef.add_recipe "hello::default"
    chef.json = {
      "hello" => {
        "name" => "dude"
      }
    }
  end
end